builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/sendmail/
  goos:
  - darwin
  - linux
  - freebsd
  - windows
  ignore:
  - goos: darwin
    goarch: 386
archives:
- replacements:
    darwin: MacOSX
    freebsd: FreeBSD
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
